"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wjg6+_i7egu&g9wn760n5(dgz9grio)dd28#@4rug*q%s$6hyv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',
    'users.apps.UsersConfig',
    'login.apps.LoginConfig',
    'import_export',
    'tailwind',
    'theme', # ชื่อแอปที่เราจะสร้างเดี๋ยวนี้
    'django_browser_reload',
    'teacher.apps.TeacherConfig',
    'room.apps.RoomConfig',
    'student.apps.StudentConfig',
    'django_extensions',
    'notifications.apps.NotificationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'Autocodegrade',
            'USER': 'postgres',
            'PASSWORD': '1234',
            'HOST': 'localhost',  # Or the IP address/hostname of your PostgreSQL server
            'PORT': '5432',       # Default PostgreSQL port
        }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = "users.User"

TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Brevo แนะนำให้ใช้ TLS กับพอร์ต 587

# ค่าเหล่านี้ควรดึงมาจาก os.environ หรือ .env เพื่อความปลอดภัย
Brevo_api = os.getenv('BREVO_API_KEY')
Brevo_login = os.getenv('BREVO_LOGIN')
Brevo_default_email = os.getenv('BREVO_DEFAULT_EMAIL')


EMAIL_HOST_USER = Brevo_login    # อีเมล Login ของ Brevo
EMAIL_HOST_PASSWORD = Brevo_api # Key ที่ Gen มาตะกี้
DEFAULT_FROM_EMAIL = Brevo_default_email

BASE_URL = 'http://127.0.0.1:8000'



JAZZMIN_SETTINGS = {
    # 1. ตั้งชื่อระบบ
    "site_title": "Classroom Admin",
    "site_header": "ระบบจัดการห้องเรียน",
    "site_brand": "Autocode Grade",
    "welcome_sign": "ยินดีต้อนรับสู่ระบบจัดการการเรียนการสอน",
    "copyright": "Autocode Grade",

    # --- ส่วนสำคัญสำหรับการใช้ Custom CSS ---
    # ชี้ไปยังไฟล์ CSS ที่คุณจะสร้าง (สมมติว่าอยู่ที่ static/admin/css/custom_admin.css)

    # ---------------------------------------

    # 2. จัดลำดับแอป
    "order_with_respect_to": [
        "room",
        "users",
        "auth",
    ],

    # 3. ใส่ไอคอน
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "users.Students": "fas fa-user-graduate",
        "users.Teachers": "fas fa-chalkboard-teacher",
        "users.Users": "fas fa-id-card",
        "room.Room": "fas fa-school",
        "room.Assignment": "fas fa-book-open",
        "room.SubmissionType": "fas fa-file-code",
    },

    # 4. เมนู Top bar
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "ดูหน้าเว็บจริง (View Site)", "url": "/", "new_window": True},
    ],

    # 5. ระบบค้นหาแบบ Global
    "search_model": ["users.Students", "room.Room", "room.Assignment"],

    # UI Customizer
    "show_ui_builder": False,  # ปรับเป็น False เมื่อตกแต่งเสร็จแล้ว
    
    # 6. ตั้งค่าการแสดงผลเมนูข้าง (ทำให้ดูโปรขึ้น)
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "changeform_format": "horizontal_tabs", # แยกฟิลด์ในหน้าแก้ไขเป็น Tab ทำให้ดูง่าย
}
# Jazzmin UI Tweaks (ปรับสีและธีม)

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"