# Generated by Django 5.2.5 on 2025-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/student_images/'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teacher_images/'),
        ),
    ]
