# Generated by Django 5.2.5 on 2025-11-19 06:27

import django.db.models.deletion
import room.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_students_profile_image_teachers_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='โจทย์ที่ AI สร้าง')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ชื่อที่แสดงผล เช่น 'ไฟล์ Python', 'Google Colab Link'", max_length=100)),
                ('identifier', models.CharField(help_text="ชื่อเฉพาะสำหรับอ้างอิงในโค้ด เช่น 'PY', 'URL', 'IPYNB'", max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/files/')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='room.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='room.generatedquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.CharField(default=room.models.generate_invite_code, max_length=6, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='rooms/covers/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='joined_rooms', to='users.students')),
                ('teachers', models.ManyToManyField(blank=True, related_name='taught_rooms', to='users.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('test_case_file', models.FileField(blank=True, help_text='ไฟล์ Test Case (.json, .txt, .zip) เพื่อให้ AI ใช้อ้างอิงสร้างควิซ', null=True, upload_to=room.models.assignment_test_case_file_path)),
                ('problem_file', models.FileField(blank=True, help_text='อัปโหลดไฟล์โจทย์ (PDF, PNG, JPG)', null=True, upload_to=room.models.assignment_problem_file_path)),
                ('quiz_question_count', models.PositiveIntegerField(default=5, help_text='จำนวนคำถามในควิซที่ต้องการให้ AI สร้าง')),
                ('quiz_choice_count', models.PositiveIntegerField(default=4, help_text='จำนวนตัวเลือกในแต่ละคำถาม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='room.room')),
                ('allowed_submission_types', models.ManyToManyField(blank=True, help_text='เลือกประเภทไฟล์ที่อนุญาตให้นักเรียนส่งสำหรับงานชิ้นนี้', related_name='assignments', to='room.submissiontype')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='room.room'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_link', models.URLField(blank=True, max_length=500, null=True)),
                ('ai_score', models.IntegerField(default=0, help_text='คะแนน (เต็ม 10) ที่ได้จาก AI')),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback ที่ AI สร้างให้', null=True)),
                ('quiz_generated', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='room.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('submission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='room.submissiontype')),
            ],
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='room.submission'),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=room.models.submission_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='room.submission')),
            ],
        ),
    ]
