# Generated by Django 5.2.5 on 2025-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='quiz_score',
            field=models.IntegerField(default=0, help_text='คะแนนที่นักเรียนทำได้จาก Quiz'),
        ),
    ]
