# Generated by Django 5.2.5 on 2025-09-03 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_rooms', to='users.students'),
        ),
        migrations.AddField(
            model_name='room',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='taught_rooms', to='users.teachers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='room.room'),
        ),
    ]
