# Generated by Django 5.2.5 on 2025-11-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_submission_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedquestion',
            name='submission',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0, help_text='คะแนนที่นักเรียนทำได้')),
                ('total_questions', models.IntegerField(default=0, help_text='จำนวนข้อสอบทั้งหมดในชุดนี้')),
                ('is_completed', models.BooleanField(default=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='room.submission')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='โจทย์คำถาม')),
                ('order', models.PositiveIntegerField(default=0, help_text='ลำดับข้อ (1, 2, 3...)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='room.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='ข้อความตัวเลือก', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='ทำเครื่องหมายถ้าเป็นข้อที่ถูก')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='room.quizquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneratedChoice',
        ),
        migrations.DeleteModel(
            name='GeneratedQuestion',
        ),
    ]
