# Generated by Django 5.2.5 on 2025-09-06 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer_text', models.TextField(help_text='เก็บ text ของคำตอบที่ถูกต้องที่ AI บอกมา')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='quiz_choice_count',
            field=models.PositiveIntegerField(default=4, help_text='จำนวนตัวเลือกในแต่ละคำถาม'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='quiz_question_count',
            field=models.PositiveIntegerField(default=5, help_text='จำนวนคำถามในควิซที่ต้องการให้ AI สร้าง'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_case_file',
            field=models.FileField(blank=True, help_text='ไฟล์ Test Case (.json, .txt, .zip) เพื่อให้ AI ใช้อ้างอิงสร้างควิซ', null=True, upload_to='assignments/test_cases/'),
        ),
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/covers/'),
        ),
        migrations.CreateModel(
            name='GeneratedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='room.generatedquestion')),
            ],
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='room.generatedquiz'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='submissions/files/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_generated', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='room.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_quiz', to='room.submission'),
        ),
    ]
