# Generated by Django 5.2.5 on 2025-09-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_generatedquestion_generatedquiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ชื่อที่แสดงผล เช่น 'ไฟล์ Python', 'Google Colab Link'", max_length=100)),
                ('identifier', models.CharField(help_text="ชื่อเฉพาะสำหรับอ้างอิงในโค้ด เช่น 'PY', 'URL', 'IPYNB'", max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='allowed_submission_types',
            field=models.ManyToManyField(blank=True, help_text='เลือกประเภทไฟล์ที่อนุญาตให้นักเรียนส่งสำหรับงานชิ้นนี้', related_name='assignments', to='room.submissiontype'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='room.submissiontype'),
        ),
    ]
