# Generated by Django 5.2.5 on 2025-12-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอส่ง/รอตรวจ'), ('GRADED', 'AI ตรวจแล้ว (รออนุมัติ)'), ('PASSED', 'ผ่านแล้ว (Approved)'), ('REJECT', 'ส่งคืนให้แก้ไข (Revision)')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='ความเห็นจากอาจารย์', null=True),
        ),
    ]
