# Generated by Django 5.2.5 on 2025-12-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_submission_graded_at_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='enable_ai_quiz',
            field=models.BooleanField(default=True, help_text='เปิดให้นักเรียนสร้างแบบทดสอบจาก AI หรือไม่'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='นักเรียนกดแจ้งปัญหาการตรวจ'),
        ),
        migrations.AddField(
            model_name='submission',
            name='report_reason',
            field=models.TextField(blank=True, help_text='เหตุผลที่แจ้งปัญหา', null=True),
        ),
    ]
