# Generated by Django 5.2.5 on 2025-11-15 02:35

import django.db.models.deletion
import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_announcement_announcementfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_file',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=room.models.submission_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='room.submission')),
            ],
        ),
    ]
