# Generated by Django 5.2.5 on 2025-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_assignment_enable_ai_quiz_submission_is_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submission',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้ส่งเกินเวลา'),
        ),
    ]
