# Generated by Django 5.2.5 on 2025-11-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_submission_submitted_file_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Feedback ที่ AI สร้างให้', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_score',
            field=models.IntegerField(default=0, help_text='คะแนน (เต็ม 10) ที่ได้จาก AI'),
        ),
    ]
