# Generated by Django 5.2.5 on 2025-12-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_assignment_allow_late_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='quiz_time_limit',
            field=models.PositiveIntegerField(default=10, help_text='ระบุเวลาเป็นนาที (เช่น 15)', verbose_name='เวลาทำแบบทดสอบ (นาที)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
