# Generated by Django 5.2.5 on 2025-12-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_assignment_quiz_time_limit_quiz_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอ AI ตรวจสอบ'), ('GRADED', 'AI ตรวจแล้ว (รอครูอนุมัติ)'), ('APPROVED', 'ผ่านแล้ว (ทำ Quiz ได้)'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('REJECTED', 'ถูกตีกลับ (แก้ไขงาน)')], default='PENDING', max_length=20),
        ),
    ]
