# Generated by Django 5.2.5 on 2025-11-16 04:53

import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_submission_ai_feedback_submission_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='problem_file',
            field=models.FileField(blank=True, help_text='อัปโหลดไฟล์โจทย์ (PDF, PNG, JPG)', null=True, upload_to=room.models.assignment_problem_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='test_case_file',
            field=models.FileField(blank=True, help_text='ไฟล์ Test Case (.json, .txt, .zip) เพื่อให้ AI ใช้อ้างอิงสร้างควิซ', null=True, upload_to=room.models.assignment_test_case_file_path),
        ),
    ]
