# Generated by Django 5.2.5 on 2025-12-24 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อที่แสดงให้เห็น (เช่น Gemini 1.5 Pro)', max_length=100)),
                ('api_value', models.CharField(help_text='ค่าที่ส่งไป API (เช่น gemini-1.5-pro)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='เปิดให้เลือกใช้หรือไม่')),
            ],
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิด ระบบ AI ทั้งหมด')),
                ('api_key', models.CharField(help_text='Google Generative AI API Key', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_model', models.ForeignKey(blank=True, help_text='เลือกโมเดลที่จะใช้งานปัจจุบัน', null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.aimodeloption')),
            ],
        ),
    ]
