# Generated by Django 5.2.5 on 2025-12-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_aimodeloption_aiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ตรวจสอบเมื่อ'),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='last_status_ok',
            field=models.BooleanField(default=False, verbose_name='สถานะล่าสุด'),
        ),
    ]
